[package]
name = "sio_vm"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sio_vm"
path = "src/main.rs"

[dependencies]
internment = "0.5.4"
chumsky = { git = "https://github.com/zesterer/chumsky" }
