[unstable]
build-std = ["std", "core", "alloc", "panic_abort"]

[build]
target = "x86_64-unknown-hermit"

[target.x86_64-unknown-hermit]
runner = "qemu-system-x86_64 -cpu qemu64,apic,fsgsbase,rdtscp,xsave,xsaveopt,fxsr,rdrand -display none -smp 1 -m 64M -serial stdio -kernel ../../rusty-hermit/loader/target/x86_64-unknown-hermit-loader/release/rusty-loader -initrd"
#runner = "uhyve -v"


